---
title: "L System Fractals in R using R6 classes."
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---
## References
Prusinkiewicz, Przemyslaw, and Aristid Lindenmayer. The Algorithmic Beauty of Plants. New York u.a: Springer, 1990.

Spannbauer, Adam. OOP Fractal Trees in R with R6, ggplot2, & gganimate (part 1) https://adamspannbauer.github.io/2018/10/07/oop-fractal-trees-in-r-with-r6-ggplot2-gganimate-part-1/



```{r fractal_l.R classes, echo=TRUE, code = readLines("fractal_l.R")}

 
```

```{r}
plot_fractal_l(l_systems_row_num=15,l_systems_max_generation=4)


```

```{r}
plot_fractal_l(l_systems_row_num=16,l_systems_max_generation=6)

```
```{r}
#plot_fractal_l(l_systems_row_num=1,l_systems_max_generation=1)
```

```{r}
#plot_fractal_l(l_systems_row_num=1,l_systems_max_generation=2)
```
```{r}
#plot_fractal_l(l_systems_row_num=1,l_systems_max_generation=3)
```

```{r}
#plot_fractal_l(l_systems_row_num=2,l_systems_max_generation=2)

```

```{r}
#plot_fractal_l(l_systems_row_num=3,l_systems_max_generation=4)
```
```{r}
#plot_fractal_l(l_systems_row_num=4,l_systems_max_generation=2)
```
